[general]
import = [
    # https://github.com/alacritty/alacritty-theme
    "~/.config/alacritty/alacritty-theme/themes/nord.toml"
]

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
LANG = "en_US.UTF-8"

[window]
dynamic_padding = true
decorations = "None"
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 15
y = 15

[font]
size = 14

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[colors]
draw_bold_text_with_bright_colors = true

[terminal.shell]
args = ["--login", "-c", "tmux attach || tmux"]
program = "/usr/bin/zsh"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mods = "Control"
